Traceback (most recent call last):
  File "/disk/homedisk/home/user293/Documents/selections/python/BatchOutputs/Test_07-11-24_12:56:47/TestRun.py", line 2, in <module>
    with open("t=300/test.txt","w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 't=300/test.txt'
